repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(.bumpversion.cfg)$'
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter
        files: '^[A-Z]+\.rst$'
  - repo: https://github.com/seantis/pre-commit-hooks
    rev: v1.1.0
    hooks:
      - id: nocheckin
        exclude: .pre-commit-config.yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [ "--fix" ]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-type-checking
        files: '^(sedate/.*|tests/.*)\.py$'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        files: '^sedate/.*\.py$'
        additional_dependencies:
          - types_pytz